---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: i want to install webserver on ubuntu
    apt: 
      name: "{{mywebpackonubuntu}}"
      state: present

  - name: i want to start webserver on ubuntu
    service: 
      name: "{{mywebpackonubuntu}}"
      state: started

  - name: i want to install webserver on RedHat
    yum: 
      name: "{{mywebpackonredhat}}"
      state: present

  - name: i want to install webserver on RedHat
    service: 
      name: "{{mywebpackonredhat}}"
      state: started           
      
